### ISSUE TITLE
Incorrect binary file in swampctf19/pwn/dream_heaps

### ISSUE THREAD

**Issue by 0xdd96** [guyinatuxedo/ctf#1]
Hello, the binary file of dream_heaps for swampctf19 seems to be uploaded incorrectly, can you please update it? Thank you ~

**Comment by guyinatuxedo** [comment]
Sorry for the late response, over Christmas I took a break. The latest push should fix the issue. If for some reason it didn't, https://github.com/guyinatuxedo/nightmare should have what you're looking for.
